# Generated by Django 2.2.4 on 2022-06-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreads', '0002_auto_20220620_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='users',
            new_name='reviews',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
